name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache toolchain
      uses: actions/cache@v2
      with:
        path: tools/toolchain
              !tools/toolchain/src
        key: ${{ runner.os }}-toolchain-${{ hashFiles('tools/toolchain/**') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-

    - name: Set up toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build toolchain if not cached
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd tools
        sh build_toolchain.sh toolchain
        cd ..

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build project
      run: cmake --build build

    #- name: Run tests
    #  run: |
    #    cd build
    #    ctest
